#
# (c) Jan Gehring <jan.gehring@gmail.com>
# 
# vim: set ts=3 sw=3 tw=0:
# vim: set expandtab:

use strict;
use warnings;

use Rex::IO::Client;

# the __io__ task gets executed by the agent
task __io__ => sub {

   file "/etc/resolv.conf",
      content => template("templates/etc/resolv.conf", cmdb_get("service://ntp/configuration"));

};

